data_json = {'city': {'coord': {'lat': 49.0562, 'lon': 44.0345},
          'country': 'RU',
          'id': 472755,
          'name': 'Сады Придонья',
          'population': 0,
          'sunrise': 1705121670,
          'sunset': 1705152573,
          'timezone': 10800},
 'cnt': 40,
 'cod': '200',
 'list': [{'clouds': {'all': 6},
           'dt': 1705158000,
           'dt_txt': '2024-01-13 15:00:00',
           'main': {'feels_like': -22.64,
                    'grnd_level': 1015,
                    'humidity': 94,
                    'pressure': 1021,
                    'sea_level': 1021,
                    'temp': -16.66,
                    'temp_kf': 2,
                    'temp_max': -16.66,
                    'temp_min': -18.66},
           'pop': 0,
           'sys': {'pod': 'n'},
           'visibility': 10000,
           'weather': [{'description': 'ясно',
                        'icon': '01n',
                        'id': 800,
                        'main': 'Clear'}],
           'wind': {'deg': 277, 'gust': 3.29, 'speed': 2.43}},
          {'clouds': {'all': 6},
           'dt': 1705168800,
           'dt_txt': '2024-01-13 18:00:00',
           'main': {'feels_like': -23.16,
                    'grnd_level': 1017,
                    'humidity': 95,
                    'pressure': 1021,
                    'sea_level': 1021,
                    'temp': -17.92,
                    'temp_kf': 2.51,
                    'temp_max': -17.92,
                    'temp_min': -20.43},
           'pop': 0,
           'sys': {'pod': 'n'},
           'visibility': 10000,
           'weather': [{'description': 'ясно',
                        'icon': '01n',
                        'id': 800,
                        'main': 'Clear'}],
           'wind': {'deg': 276, 'gust': 1.94, 'speed': 1.92}},
          {'clouds': {'all': 5},
           'dt': 1705179600,
           'dt_txt': '2024-01-13 21:00:00',
           'main': {'feels_like': -24.84,
                    'grnd_level': 1018,
                    'humidity': 96,
                    'pressure': 1023,
                    'sea_level': 1023,
                    'temp': -19.78,
                    'temp_kf': 1.56,
                    'temp_max': -19.78,
                    'temp_min': -21.34},
           'pop': 0,
           'sys': {'pod': 'n'},
           'visibility': 10000,
           'weather': [{'description': 'ясно',
                        'icon': '01n',
                        'id': 800,
                        'main': 'Clear'}],
           'wind': {'deg': 246, 'gust': 1.66, 'speed': 1.71}},
          {'clouds': {'all': 6},
           'dt': 1705190400,
           'dt_txt': '2024-01-14 00:00:00',
           'main': {'feels_like': -26.06,
                    'grnd_level': 1018,
                    'humidity': 97,
                    'pressure': 1024,
                    'sea_level': 1024,
                    'temp': -21.62,
                    'temp_kf': 0,
                    'temp_max': -21.62,
                    'temp_min': -21.62},
           'pop': 0,
           'sys': {'pod': 'n'},
           'visibility': 10000,
           'weather': [{'description': 'ясно',
                        'icon': '01n',
                        'id': 800,
                        'main': 'Clear'}],
           'wind': {'deg': 243, 'gust': 1.4, 'speed': 1.38}},
          {'clouds': {'all': 10},
           'dt': 1705201200,
           'dt_txt': '2024-01-14 03:00:00',
           'main': {'feels_like': -27.29,
                    'grnd_level': 1018,
                    'humidity': 99,
                    'pressure': 1024,
                    'sea_level': 1024,
                    'temp': -21.36,
                    'temp_kf': 0,
                    'temp_max': -21.36,
                    'temp_min': -21.36},
           'pop': 0,
           'sys': {'pod': 'n'},
           'visibility': 10000,
           'weather': [{'description': 'ясно',
                        'icon': '01n',
                        'id': 800,
                        'main': 'Clear'}],
           'wind': {'deg': 206, 'gust': 2.02, 'speed': 1.98}},
          {'clouds': {'all': 28},
           'dt': 1705212000,
           'dt_txt': '2024-01-14 06:00:00',
           'main': {'feels_like': -25.77,
                    'grnd_level': 1019,
                    'humidity': 98,
                    'pressure': 1025,
                    'sea_level': 1025,
                    'temp': -18.77,
                    'temp_kf': 0,
                    'temp_max': -18.77,
                    'temp_min': -18.77},
           'pop': 0,
           'sys': {'pod': 'd'},
           'visibility': 10000,
           'weather': [{'description': 'переменная облачность',
                        'icon': '03d',
                        'id': 802,
                        'main': 'Clouds'}],
           'wind': {'deg': 190, 'gust': 5.49, 'speed': 3.07}},
          {'clouds': {'all': 16},
           'dt': 1705222800,
           'dt_txt': '2024-01-14 09:00:00',
           'main': {'feels_like': -19.41,
                    'grnd_level': 1019,
                    'humidity': 85,
                    'pressure': 1025,
                    'sea_level': 1025,
                    'temp': -12.41,
                    'temp_kf': 0,
                    'temp_max': -12.41,
                    'temp_min': -12.41},
           'pop': 0,
           'sys': {'pod': 'd'},
           'visibility': 10000,
           'weather': [{'description': 'небольшая облачность',
                        'icon': '02d',
                        'id': 801,
                        'main': 'Clouds'}],
           'wind': {'deg': 191, 'gust': 7.98, 'speed': 4.39}},
          {'clouds': {'all': 14},
           'dt': 1705233600,
           'dt_txt': '2024-01-14 12:00:00',
           'main': {'feels_like': -17.42,
                    'grnd_level': 1017,
                    'humidity': 86,
                    'pressure': 1023,
                    'sea_level': 1023,
                    'temp': -10.42,
                    'temp_kf': 0,
                    'temp_max': -10.42,
                    'temp_min': -10.42},
           'pop': 0,
           'sys': {'pod': 'd'},
           'visibility': 10000,
           'weather': [{'description': 'небольшая облачность',
                        'icon': '02d',
                        'id': 801,
                        'main': 'Clouds'}],
           'wind': {'deg': 159, 'gust': 10.88, 'speed': 5.09}},
          {'clouds': {'all': 8},
           'dt': 1705244400,
           'dt_txt': '2024-01-14 15:00:00',
           'main': {'feels_like': -19.11,
                    'grnd_level': 1016,
                    'humidity': 92,
                    'pressure': 1022,
                    'sea_level': 1022,
                    'temp': -12.11,
                    'temp_kf': 0,
                    'temp_max': -12.11,
                    'temp_min': -12.11},
           'pop': 0,
           'sys': {'pod': 'n'},
           'visibility': 10000,
           'weather': [{'description': 'ясно',
                        'icon': '01n',
                        'id': 800,
                        'main': 'Clear'}],
           'wind': {'deg': 158, 'gust': 14.79, 'speed': 6.13}},
          {'clouds': {'all': 20},
           'dt': 1705255200,
           'dt_txt': '2024-01-14 18:00:00',
           'main': {'feels_like': -17.76,
                    'grnd_level': 1015,
                    'humidity': 84,
                    'pressure': 1021,
                    'sea_level': 1021,
                    'temp': -10.76,
                    'temp_kf': 0,
                    'temp_max': -10.76,
                    'temp_min': -10.76},
           'pop': 0,
           'sys': {'pod': 'n'},
           'visibility': 10000,
           'weather': [{'description': 'небольшая облачность',
                        'icon': '02n',
                        'id': 801,
                        'main': 'Clouds'}],
           'wind': {'deg': 167, 'gust': 16.42, 'speed': 7.12}},
          {'clouds': {'all': 100},
           'dt': 1705266000,
           'dt_txt': '2024-01-14 21:00:00',
           'main': {'feels_like': -15.4,
                    'grnd_level': 1014,
                    'humidity': 84,
                    'pressure': 1019,
                    'sea_level': 1019,
                    'temp': -8.4,
                    'temp_kf': 0,
                    'temp_max': -8.4,
                    'temp_min': -8.4},
           'pop': 0,
           'sys': {'pod': 'n'},
           'visibility': 10000,
           'weather': [{'description': 'пасмурно',
                        'icon': '04n',
                        'id': 804,
                        'main': 'Clouds'}],
           'wind': {'deg': 172, 'gust': 17.9, 'speed': 8.32}},
          {'clouds': {'all': 100},
           'dt': 1705276800,
           'dt_txt': '2024-01-15 00:00:00',
           'main': {'feels_like': -12.99,
                    'grnd_level': 1012,
                    'humidity': 87,
                    'pressure': 1017,
                    'sea_level': 1017,
                    'temp': -5.99,
                    'temp_kf': 0,
                    'temp_max': -5.99,
                    'temp_min': -5.99},
           'pop': 0.07,
           'sys': {'pod': 'n'},
           'visibility': 10000,
           'weather': [{'description': 'пасмурно',
                        'icon': '04n',
                        'id': 804,
                        'main': 'Clouds'}],
           'wind': {'deg': 178, 'gust': 18.99, 'speed': 9.04}},
          {'clouds': {'all': 100},
           'dt': 1705287600,
           'dt_txt': '2024-01-15 03:00:00',
           'main': {'feels_like': -11.59,
                    'grnd_level': 1010,
                    'humidity': 86,
                    'pressure': 1015,
                    'sea_level': 1015,
                    'temp': -4.59,
                    'temp_kf': 0,
                    'temp_max': -4.59,
                    'temp_min': -4.59},
           'pop': 0.04,
           'sys': {'pod': 'n'},
           'visibility': 10000,
           'weather': [{'description': 'пасмурно',
                        'icon': '04n',
                        'id': 804,
                        'main': 'Clouds'}],
           'wind': {'deg': 176, 'gust': 19.81, 'speed': 10.11}},
          {'clouds': {'all': 100},
           'dt': 1705298400,
           'dt_txt': '2024-01-15 06:00:00',
           'main': {'feels_like': -11,
                    'grnd_level': 1010,
                    'humidity': 91,
                    'pressure': 1016,
                    'sea_level': 1016,
                    'temp': -4,
                    'temp_kf': 0,
                    'temp_max': -4,
                    'temp_min': -4},
           'pop': 0.34,
           'snow': {'3h': 0.31},
           'sys': {'pod': 'd'},
           'visibility': 1804,
           'weather': [{'description': 'небольшой снег',
                        'icon': '13d',
                        'id': 600,
                        'main': 'Snow'}],
           'wind': {'deg': 180, 'gust': 18.53, 'speed': 9.31}},
          {'clouds': {'all': 100},
           'dt': 1705309200,
           'dt_txt': '2024-01-15 09:00:00',
           'main': {'feels_like': -8.93,
                    'grnd_level': 1010,
                    'humidity': 92,
                    'pressure': 1015,
                    'sea_level': 1015,
                    'temp': -1.93,
                    'temp_kf': 0,
                    'temp_max': -1.93,
                    'temp_min': -1.93},
           'pop': 0.7,
           'snow': {'3h': 0.62},
           'sys': {'pod': 'd'},
           'visibility': 1044,
           'weather': [{'description': 'небольшой снег',
                        'icon': '13d',
                        'id': 600,
                        'main': 'Snow'}],
           'wind': {'deg': 189, 'gust': 16.78, 'speed': 8.77}},
          {'clouds': {'all': 100},
           'dt': 1705320000,
           'dt_txt': '2024-01-15 12:00:00',
           'main': {'feels_like': -7.9,
                    'grnd_level': 1009,
                    'humidity': 92,
                    'pressure': 1015,
                    'sea_level': 1015,
                    'temp': -1.15,
                    'temp_kf': 0,
                    'temp_max': -1.15,
                    'temp_min': -1.15},
           'pop': 0.87,
           'snow': {'3h': 0.52},
           'sys': {'pod': 'd'},
           'visibility': 5816,
           'weather': [{'description': 'небольшой снег',
                        'icon': '13d',
                        'id': 600,
                        'main': 'Snow'}],
           'wind': {'deg': 193, 'gust': 13.83, 'speed': 8.2}},
          {'clouds': {'all': 100},
           'dt': 1705330800,
           'dt_txt': '2024-01-15 15:00:00',
           'main': {'feels_like': -8.16,
                    'grnd_level': 1010,
                    'humidity': 95,
                    'pressure': 1015,
                    'sea_level': 1015,
                    'temp': -1.68,
                    'temp_kf': 0,
                    'temp_max': -1.68,
                    'temp_min': -1.68},
           'pop': 0.44,
           'snow': {'3h': 0.16},
           'sys': {'pod': 'n'},
           'visibility': 1274,
           'weather': [{'description': 'небольшой снег',
                        'icon': '13n',
                        'id': 600,
                        'main': 'Snow'}],
           'wind': {'deg': 186, 'gust': 13.58, 'speed': 7.18}},
          {'clouds': {'all': 100},
           'dt': 1705341600,
           'dt_txt': '2024-01-15 18:00:00',
           'main': {'feels_like': -7.47,
                    'grnd_level': 1010,
                    'humidity': 95,
                    'pressure': 1015,
                    'sea_level': 1015,
                    'temp': -1.06,
                    'temp_kf': 0,
                    'temp_max': -1.06,
                    'temp_min': -1.06},
           'pop': 0.45,
           'snow': {'3h': 0.17},
           'sys': {'pod': 'n'},
           'visibility': 3135,
           'weather': [{'description': 'небольшой снег',
                        'icon': '13n',
                        'id': 600,
                        'main': 'Snow'}],
           'wind': {'deg': 191, 'gust': 14.02, 'speed': 7.44}},
          {'clouds': {'all': 100},
           'dt': 1705352400,
           'dt_txt': '2024-01-15 21:00:00',
           'main': {'feels_like': -7.2,
                    'grnd_level': 1010,
                    'humidity': 89,
                    'pressure': 1015,
                    'sea_level': 1015,
                    'temp': -0.99,
                    'temp_kf': 0,
                    'temp_max': -0.99,
                    'temp_min': -0.99},
           'pop': 0.68,
           'snow': {'3h': 0.8},
           'sys': {'pod': 'n'},
           'visibility': 2404,
           'weather': [{'description': 'небольшой снег',
                        'icon': '13n',
                        'id': 600,
                        'main': 'Snow'}],
           'wind': {'deg': 192, 'gust': 15.63, 'speed': 7.02}},
          {'clouds': {'all': 99},
           'dt': 1705363200,
           'dt_txt': '2024-01-16 00:00:00',
           'main': {'feels_like': -6.23,
                    'grnd_level': 1010,
                    'humidity': 79,
                    'pressure': 1015,
                    'sea_level': 1015,
                    'temp': -0.59,
                    'temp_kf': 0,
                    'temp_max': -0.59,
                    'temp_min': -0.59},
           'pop': 0.66,
           'snow': {'3h': 0.3},
           'sys': {'pod': 'n'},
           'visibility': 10000,
           'weather': [{'description': 'небольшой снег',
                        'icon': '13n',
                        'id': 600,
                        'main': 'Snow'}],
           'wind': {'deg': 185, 'gust': 14.69, 'speed': 6.07}},
          {'clouds': {'all': 100},
           'dt': 1705374000,
           'dt_txt': '2024-01-16 03:00:00',
           'main': {'feels_like': -7.97,
                    'grnd_level': 1009,
                    'humidity': 77,
                    'pressure': 1014,
                    'sea_level': 1014,
                    'temp': -2.24,
                    'temp_kf': 0,
                    'temp_max': -2.24,
                    'temp_min': -2.24},
           'pop': 0.1,
           'sys': {'pod': 'n'},
           'visibility': 10000,
           'weather': [{'description': 'пасмурно',
                        'icon': '04n',
                        'id': 804,
                        'main': 'Clouds'}],
           'wind': {'deg': 175, 'gust': 13.88, 'speed': 5.42}},
          {'clouds': {'all': 100},
           'dt': 1705384800,
           'dt_txt': '2024-01-16 06:00:00',
           'main': {'feels_like': -9.18,
                    'grnd_level': 1009,
                    'humidity': 75,
                    'pressure': 1015,
                    'sea_level': 1015,
                    'temp': -2.66,
                    'temp_kf': 0,
                    'temp_max': -2.66,
                    'temp_min': -2.66},
           'pop': 0.01,
           'sys': {'pod': 'd'},
           'visibility': 10000,
           'weather': [{'description': 'пасмурно',
                        'icon': '04d',
                        'id': 804,
                        'main': 'Clouds'}],
           'wind': {'deg': 169, 'gust': 17.19, 'speed': 6.68}},
          {'clouds': {'all': 100},
           'dt': 1705395600,
           'dt_txt': '2024-01-16 09:00:00',
           'main': {'feels_like': -4.46,
                    'grnd_level': 1007,
                    'humidity': 81,
                    'pressure': 1012,
                    'sea_level': 1012,
                    'temp': 1.67,
                    'temp_kf': 0,
                    'temp_max': 1.67,
                    'temp_min': 1.67},
           'pop': 0,
           'sys': {'pod': 'd'},
           'visibility': 10000,
           'weather': [{'description': 'пасмурно',
                        'icon': '04d',
                        'id': 804,
                        'main': 'Clouds'}],
           'wind': {'deg': 174, 'gust': 21.05, 'speed': 8.88}},
          {'clouds': {'all': 100},
           'dt': 1705406400,
           'dt_txt': '2024-01-16 12:00:00',
           'main': {'feels_like': -3.92,
                    'grnd_level': 1005,
                    'humidity': 93,
                    'pressure': 1011,
                    'sea_level': 1011,
                    'temp': 1.94,
                    'temp_kf': 0,
                    'temp_max': 1.94,
                    'temp_min': 1.94},
           'pop': 0.2,
           'rain': {'3h': 0.18},
           'sys': {'pod': 'd'},
           'visibility': 10000,
           'weather': [{'description': 'небольшой дождь',
                        'icon': '10d',
                        'id': 500,
                        'main': 'Rain'}],
           'wind': {'deg': 165, 'gust': 16.31, 'speed': 8.33}},
          {'clouds': {'all': 100},
           'dt': 1705417200,
           'dt_txt': '2024-01-16 15:00:00',
           'main': {'feels_like': -5.04,
                    'grnd_level': 1004,
                    'humidity': 94,
                    'pressure': 1009,
                    'sea_level': 1009,
                    'temp': 1.62,
                    'temp_kf': 0,
                    'temp_max': 1.62,
                    'temp_min': 1.62},
           'pop': 0,
           'sys': {'pod': 'n'},
           'visibility': 10000,
           'weather': [{'description': 'пасмурно',
                        'icon': '04n',
                        'id': 804,
                        'main': 'Clouds'}],
           'wind': {'deg': 160, 'gust': 19.78, 'speed': 10.5}},
          {'clouds': {'all': 100},
           'dt': 1705428000,
           'dt_txt': '2024-01-16 18:00:00',
           'main': {'feels_like': -4.48,
                    'grnd_level': 1003,
                    'humidity': 97,
                    'pressure': 1008,
                    'sea_level': 1008,
                    'temp': 1.74,
                    'temp_kf': 0,
                    'temp_max': 1.74,
                    'temp_min': 1.74},
           'pop': 0.22,
           'rain': {'3h': 0.29},
           'sys': {'pod': 'n'},
           'visibility': 10000,
           'weather': [{'description': 'небольшой дождь',
                        'icon': '10n',
                        'id': 500,
                        'main': 'Rain'}],
           'wind': {'deg': 172, 'gust': 17.17, 'speed': 9.21}},
          {'clouds': {'all': 100},
           'dt': 1705438800,
           'dt_txt': '2024-01-16 21:00:00',
           'main': {'feels_like': -4.83,
                    'grnd_level': 1001,
                    'humidity': 98,
                    'pressure': 1006,
                    'sea_level': 1006,
                    'temp': 1.47,
                    'temp_kf': 0,
                    'temp_max': 1.47,
                    'temp_min': 1.47},
           'pop': 0.62,
           'snow': {'3h': 0.25},
           'sys': {'pod': 'n'},
           'visibility': 471,
           'weather': [{'description': 'небольшой снег',
                        'icon': '13n',
                        'id': 600,
                        'main': 'Snow'}],
           'wind': {'deg': 171, 'gust': 16.63, 'speed': 9.18}},
          {'clouds': {'all': 100},
           'dt': 1705449600,
           'dt_txt': '2024-01-17 00:00:00',
           'main': {'feels_like': -4.26,
                    'grnd_level': 999,
                    'humidity': 96,
                    'pressure': 1004,
                    'sea_level': 1004,
                    'temp': 2,
                    'temp_kf': 0,
                    'temp_max': 2,
                    'temp_min': 2},
           'pop': 1,
           'rain': {'3h': 3.98},
           'sys': {'pod': 'n'},
           'visibility': 7978,
           'weather': [{'description': 'дождь',
                        'icon': '10n',
                        'id': 501,
                        'main': 'Rain'}],
           'wind': {'deg': 183, 'gust': 19.96, 'speed': 9.59}},
          {'clouds': {'all': 100},
           'dt': 1705460400,
           'dt_txt': '2024-01-17 03:00:00',
           'main': {'feels_like': -6.37,
                    'grnd_level': 1004,
                    'humidity': 90,
                    'pressure': 1010,
                    'sea_level': 1010,
                    'temp': -0.19,
                    'temp_kf': 0,
                    'temp_max': -0.19,
                    'temp_min': -0.19},
           'pop': 1,
           'snow': {'3h': 2.33},
           'sys': {'pod': 'n'},
           'visibility': 10000,
           'weather': [{'description': 'снег',
                        'icon': '13n',
                        'id': 601,
                        'main': 'Snow'}],
           'wind': {'deg': 300, 'gust': 14.01, 'speed': 7.49}},
          {'clouds': {'all': 87},
           'dt': 1705471200,
           'dt_txt': '2024-01-17 06:00:00',
           'main': {'feels_like': -11.26,
                    'grnd_level': 1011,
                    'humidity': 84,
                    'pressure': 1016,
                    'sea_level': 1016,
                    'temp': -4.26,
                    'temp_kf': 0,
                    'temp_max': -4.26,
                    'temp_min': -4.26},
           'pop': 0.8,
           'sys': {'pod': 'd'},
           'visibility': 10000,
           'weather': [{'description': 'пасмурно',
                        'icon': '04d',
                        'id': 804,
                        'main': 'Clouds'}],
           'wind': {'deg': 283, 'gust': 14, 'speed': 7.76}},
          {'clouds': {'all': 15},
           'dt': 1705482000,
           'dt_txt': '2024-01-17 09:00:00',
           'main': {'feels_like': -13.33,
                    'grnd_level': 1015,
                    'humidity': 82,
                    'pressure': 1021,
                    'sea_level': 1021,
                    'temp': -6.33,
                    'temp_kf': 0,
                    'temp_max': -6.33,
                    'temp_min': -6.33},
           'pop': 0,
           'sys': {'pod': 'd'},
           'visibility': 10000,
           'weather': [{'description': 'небольшая облачность',
                        'icon': '02d',
                        'id': 801,
                        'main': 'Clouds'}],
           'wind': {'deg': 290, 'gust': 13.88, 'speed': 7.49}},
          {'clouds': {'all': 18},
           'dt': 1705492800,
           'dt_txt': '2024-01-17 12:00:00',
           'main': {'feels_like': -13.97,
                    'grnd_level': 1019,
                    'humidity': 78,
                    'pressure': 1025,
                    'sea_level': 1025,
                    'temp': -6.97,
                    'temp_kf': 0,
                    'temp_max': -6.97,
                    'temp_min': -6.97},
           'pop': 0,
           'sys': {'pod': 'd'},
           'visibility': 10000,
           'weather': [{'description': 'небольшая облачность',
                        'icon': '02d',
                        'id': 801,
                        'main': 'Clouds'}],
           'wind': {'deg': 297, 'gust': 13.18, 'speed': 6.82}},
          {'clouds': {'all': 2},
           'dt': 1705503600,
           'dt_txt': '2024-01-17 15:00:00',
           'main': {'feels_like': -15.2,
                    'grnd_level': 1023,
                    'humidity': 82,
                    'pressure': 1029,
                    'sea_level': 1029,
                    'temp': -8.84,
                    'temp_kf': 0,
                    'temp_max': -8.84,
                    'temp_min': -8.84},
           'pop': 0,
           'sys': {'pod': 'n'},
           'visibility': 10000,
           'weather': [{'description': 'ясно',
                        'icon': '01n',
                        'id': 800,
                        'main': 'Clear'}],
           'wind': {'deg': 292, 'gust': 10.03, 'speed': 4.06}},
          {'clouds': {'all': 4},
           'dt': 1705514400,
           'dt_txt': '2024-01-17 18:00:00',
           'main': {'feels_like': -14.94,
                    'grnd_level': 1026,
                    'humidity': 89,
                    'pressure': 1032,
                    'sea_level': 1032,
                    'temp': -9.86,
                    'temp_kf': 0,
                    'temp_max': -9.86,
                    'temp_min': -9.86},
           'pop': 0,
           'sys': {'pod': 'n'},
           'visibility': 10000,
           'weather': [{'description': 'ясно',
                        'icon': '01n',
                        'id': 800,
                        'main': 'Clear'}],
           'wind': {'deg': 266, 'gust': 6.5, 'speed': 2.68}},
          {'clouds': {'all': 6},
           'dt': 1705525200,
           'dt_txt': '2024-01-17 21:00:00',
           'main': {'feels_like': -14.97,
                    'grnd_level': 1028,
                    'humidity': 90,
                    'pressure': 1033,
                    'sea_level': 1033,
                    'temp': -10.53,
                    'temp_kf': 0,
                    'temp_max': -10.53,
                    'temp_min': -10.53},
           'pop': 0,
           'sys': {'pod': 'n'},
           'visibility': 10000,
           'weather': [{'description': 'ясно',
                        'icon': '01n',
                        'id': 800,
                        'main': 'Clear'}],
           'wind': {'deg': 253, 'gust': 2.87, 'speed': 2.15}},
          {'clouds': {'all': 5},
           'dt': 1705536000,
           'dt_txt': '2024-01-18 00:00:00',
           'main': {'feels_like': -15.16,
                    'grnd_level': 1028,
                    'humidity': 92,
                    'pressure': 1034,
                    'sea_level': 1034,
                    'temp': -11.06,
                    'temp_kf': 0,
                    'temp_max': -11.06,
                    'temp_min': -11.06},
           'pop': 0,
           'sys': {'pod': 'n'},
           'visibility': 10000,
           'weather': [{'description': 'ясно',
                        'icon': '01n',
                        'id': 800,
                        'main': 'Clear'}],
           'wind': {'deg': 226, 'gust': 2.07, 'speed': 1.9}},
          {'clouds': {'all': 5},
           'dt': 1705546800,
           'dt_txt': '2024-01-18 03:00:00',
           'main': {'feels_like': -16.07,
                    'grnd_level': 1029,
                    'humidity': 92,
                    'pressure': 1034,
                    'sea_level': 1034,
                    'temp': -11.44,
                    'temp_kf': 0,
                    'temp_max': -11.44,
                    'temp_min': -11.44},
           'pop': 0,
           'sys': {'pod': 'n'},
           'visibility': 10000,
           'weather': [{'description': 'ясно',
                        'icon': '01n',
                        'id': 800,
                        'main': 'Clear'}],
           'wind': {'deg': 209, 'gust': 2.43, 'speed': 2.17}},
          {'clouds': {'all': 5},
           'dt': 1705557600,
           'dt_txt': '2024-01-18 06:00:00',
           'main': {'feels_like': -16.08,
                    'grnd_level': 1029,
                    'humidity': 90,
                    'pressure': 1035,
                    'sea_level': 1035,
                    'temp': -10.5,
                    'temp_kf': 0,
                    'temp_max': -10.5,
                    'temp_min': -10.5},
           'pop': 0,
           'sys': {'pod': 'd'},
           'visibility': 10000,
           'weather': [{'description': 'ясно',
                        'icon': '01d',
                        'id': 800,
                        'main': 'Clear'}],
           'wind': {'deg': 177, 'gust': 6.2, 'speed': 2.97}},
          {'clouds': {'all': 9},
           'dt': 1705568400,
           'dt_txt': '2024-01-18 09:00:00',
           'main': {'feels_like': -14.06,
                    'grnd_level': 1028,
                    'humidity': 78,
                    'pressure': 1034,
                    'sea_level': 1034,
                    'temp': -7.06,
                    'temp_kf': 0,
                    'temp_max': -7.06,
                    'temp_min': -7.06},
           'pop': 0,
           'sys': {'pod': 'd'},
           'visibility': 10000,
           'weather': [{'description': 'ясно',
                        'icon': '01d',
                        'id': 800,
                        'main': 'Clear'}],
           'wind': {'deg': 164, 'gust': 10.83, 'speed': 5.83}},
          {'clouds': {'all': 11},
           'dt': 1705579200,
           'dt_txt': '2024-01-18 12:00:00',
           'main': {'feels_like': -13.17,
                    'grnd_level': 1026,
                    'humidity': 83,
                    'pressure': 1032,
                    'sea_level': 1032,
                    'temp': -6.17,
                    'temp_kf': 0,
                    'temp_max': -6.17,
                    'temp_min': -6.17},
           'pop': 0,
           'sys': {'pod': 'd'},
           'visibility': 10000,
           'weather': [{'description': 'небольшая облачность',
                        'icon': '02d',
                        'id': 801,
                        'main': 'Clouds'}],
           'wind': {'deg': 157, 'gust': 12.8, 'speed': 6.5}}],
 'message': 0}
